-- !!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!
-- !!! TODO RUN ON PROD — multi-chain deposit wallet config.  !!!
-- !!! Seeds one app_settings key per extra chain with the    !!!
-- !!! REAL receiving address (generated by                   !!!
-- !!! scripts/generate-wallets.js — keys live only in the    !!!
-- !!! gitignored scripts/.wallets.secret.json).              !!!
-- !!! Same address per network: one TRON addr → TRX +        !!!
-- !!! USDT-TRC20; one EVM addr → ETH/BNB + USDT/USDC on       !!!
-- !!! ERC20 & BEP20; BTC; LTC.                                !!!
-- !!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!
-- =============================================
-- Crypto deposit wallets (TRC20/BEP20/ERC20/BTC/ETH/BNB/TRX/LTC)
-- =============================================
--
-- TON / USDT(TON) keep their hardcoded Highload-V3 address in
-- src/lib/addresses.js — untouched. The frontend already falls
-- back to the same addresses (addresses.js DEPOSIT_ADDRESSES) so
-- the sheet works even before this runs; seeding the DB lets an
-- admin override any of them later from Admin → Control.
--
-- INSERT … ON CONFLICT DO NOTHING keeps any admin-set value, and
-- the follow-up UPDATE only fills rows that are still blank — so
-- re-running is always safe and never clobbers a changed wallet.

INSERT INTO app_settings (key, value) VALUES
-- Defaults = the HD-index-0 treasury (single canonical hot
-- wallet; the legacy generate-wallets.js addresses are retired).
  ('deposit_addr_usdt_trc20', '"TNLov2u5DuHKiSJpQHziqb8Gcov2GQWZw4"'::jsonb),
  ('deposit_addr_trx',        '"TNLov2u5DuHKiSJpQHziqb8Gcov2GQWZw4"'::jsonb),
  ('deposit_addr_eth',        '"0x71740514b90aC31d0Ba0fF772107Ab5bA8496Ac2"'::jsonb),
  ('deposit_addr_bnb',        '"0x71740514b90aC31d0Ba0fF772107Ab5bA8496Ac2"'::jsonb),
  ('deposit_addr_usdt_erc20', '"0x71740514b90aC31d0Ba0fF772107Ab5bA8496Ac2"'::jsonb),
  ('deposit_addr_usdc_erc20', '"0x71740514b90aC31d0Ba0fF772107Ab5bA8496Ac2"'::jsonb),
  ('deposit_addr_usdt_bep20', '"0x71740514b90aC31d0Ba0fF772107Ab5bA8496Ac2"'::jsonb),
  ('deposit_addr_usdc_bep20', '"0x71740514b90aC31d0Ba0fF772107Ab5bA8496Ac2"'::jsonb),
  ('deposit_addr_btc',        '"bc1qprd6zdx8kv73xup6ed9rypnedxcltm89k8pfzk"'::jsonb),
  ('deposit_addr_ltc',        '"ltc1qc65xapvmpzqesmvajncddleww3gxuy7z7jku6g"'::jsonb)
ON CONFLICT (key) DO NOTHING;

-- Consolidate: rewrite rows still on the OLD empty default ('')
-- OR the retired legacy generate-wallets.js addresses → the
-- HD-index-0 treasury. A custom admin-set address is untouched.
UPDATE app_settings SET value = '"TNLov2u5DuHKiSJpQHziqb8Gcov2GQWZw4"'::jsonb
  WHERE key IN ('deposit_addr_usdt_trc20','deposit_addr_trx')
    AND value IN ('""'::jsonb, '"TAajZiWyXR2RwBZ4WhJUbJqGsaboCBtFZj"'::jsonb);
UPDATE app_settings SET value = '"0x71740514b90aC31d0Ba0fF772107Ab5bA8496Ac2"'::jsonb
  WHERE key IN ('deposit_addr_eth','deposit_addr_bnb','deposit_addr_usdt_erc20',
                'deposit_addr_usdc_erc20','deposit_addr_usdt_bep20','deposit_addr_usdc_bep20')
    AND value IN ('""'::jsonb, '"0x8a224AcBc5c5cc034CB72CA921C4e25F02C90848"'::jsonb);
UPDATE app_settings SET value = '"bc1qprd6zdx8kv73xup6ed9rypnedxcltm89k8pfzk"'::jsonb
  WHERE key = 'deposit_addr_btc'
    AND value IN ('""'::jsonb, '"bc1qphuhskgp025vmvvkyjelckkr8hgyqzvpfskem7"'::jsonb);
UPDATE app_settings SET value = '"ltc1qc65xapvmpzqesmvajncddleww3gxuy7z7jku6g"'::jsonb
  WHERE key = 'deposit_addr_ltc'
    AND value IN ('""'::jsonb, '"ltc1qyfhfwzpyvf846jn6zsnndqfswl64nelm6j07q6"'::jsonb);

NOTIFY pgrst, 'reload schema';
