-- English translations for batch 2 (300 questions)

-- 1-30: Science
UPDATE questions SET question_en = 'Which element of the periodic table has the symbol Au?', options_en = '["Silver","Aluminum","Gold","Argon"]' WHERE question = 'Какой элемент таблицы Менделеева имеет символ Au?';
UPDATE questions SET question_en = 'What does a barometer measure?', options_en = '["Temperature","Humidity","Atmospheric pressure","Wind speed"]' WHERE question = 'Что измеряет барометр?';
UPDATE questions SET question_en = 'Which particle has a negative charge?', options_en = '["Proton","Neutron","Electron","Positron"]' WHERE question = 'Какая частица имеет отрицательный заряд?';
UPDATE questions SET question_en = 'Which organ produces insulin?', options_en = '["Liver","Kidneys","Pancreas","Thyroid gland"]' WHERE question = 'Какой орган вырабатывает инсулин?';
UPDATE questions SET question_en = 'What is an ozone molecule made of?', options_en = '["Two oxygen atoms","Three oxygen atoms","Oxygen and nitrogen","Oxygen and hydrogen"]' WHERE question = 'Из чего состоит молекула озона?';
UPDATE questions SET question_en = 'Which scientist discovered penicillin?', options_en = '["Pasteur","Fleming","Koch","Jenner"]' WHERE question = 'Какой учёный открыл пенициллин?';
UPDATE questions SET question_en = 'What is the state of water at 0°C?', options_en = '["Only ice","Only water","Both ice and water simultaneously","Steam"]' WHERE question = 'Какое агрегатное состояние воды при 0°C?';
UPDATE questions SET question_en = 'Which acid is found in the human stomach?', options_en = '["Sulfuric","Hydrochloric","Nitric","Acetic"]' WHERE question = 'Какая кислота содержится в желудке человека?';
UPDATE questions SET question_en = 'What is a photon?', options_en = '["A particle of matter","A quantum of light","A hydrogen atom","A unit of pressure"]' WHERE question = 'Что такое фотон?';
UPDATE questions SET question_en = 'Which gas is used in welding to protect the seam?', options_en = '["Oxygen","Hydrogen","Argon","Chlorine"]' WHERE question = 'Какой газ используют при сварке для защиты шва?';
UPDATE questions SET question_en = 'How many bones are in the human hand?', options_en = '["17","22","27","32"]' WHERE question = 'Сколько костей в кисти руки человека?';
UPDATE questions SET question_en = 'Which vitamin is essential for blood clotting?', options_en = '["A","C","D","K"]' WHERE question = 'Какой витамин необходим для свёртывания крови?';
UPDATE questions SET question_en = 'What substance is the base of soap?', options_en = '["Alkali and fats","Acid and alcohol","Salt and sugar","Starch and water"]' WHERE question = 'Какое вещество является основой мыла?';
UPDATE questions SET question_en = 'How many pairs of cranial nerves does a human have?', options_en = '["8","10","12","14"]' WHERE question = 'Сколько пар черепно-мозговых нервов у человека?';
UPDATE questions SET question_en = 'Which law describes the relationship between pressure and volume of a gas at constant temperature?', options_en = '["Gay-Lussac''s Law","Charles''s Law","Boyle''s Law","Avogadro''s Law"]' WHERE question = 'Какой закон описывает связь давления и объёма газа при постоянной температуре?';
UPDATE questions SET question_en = 'What is the normal human body temperature?', options_en = '["35.5°C","36.6°C","37.2°C","38.0°C"]' WHERE question = 'Какова нормальная температура тела человека?';
UPDATE questions SET question_en = 'Which element is the lightest?', options_en = '["Helium","Hydrogen","Lithium","Carbon"]' WHERE question = 'Какой элемент самый лёгкий?';
UPDATE questions SET question_en = 'What does botany study?', options_en = '["Animals","Plants","Minerals","Stars"]' WHERE question = 'Что изучает ботаника?';
UPDATE questions SET question_en = 'Which gas supports combustion?', options_en = '["Nitrogen","Carbon dioxide","Oxygen","Helium"]' WHERE question = 'Какой газ поддерживает горение?';
UPDATE questions SET question_en = 'Which organ filters the blood?', options_en = '["Heart","Lungs","Kidneys","Stomach"]' WHERE question = 'Какой орган фильтрует кровь?';
UPDATE questions SET question_en = 'What is the instrument for measuring air humidity called?', options_en = '["Thermometer","Hygrometer","Anemometer","Speedometer"]' WHERE question = 'Как называется прибор для измерения влажности воздуха?';
UPDATE questions SET question_en = 'What type of lens is used for nearsightedness?', options_en = '["Convex","Concave","Flat","Cylindrical"]' WHERE question = 'Какой тип линзы используется при близорукости?';
UPDATE questions SET question_en = 'Which chemical element is represented by the symbol Na?', options_en = '["Nitrogen","Nickel","Sodium","Neon"]' WHERE question = 'Какой химический элемент обозначается символом Na?';
UPDATE questions SET question_en = 'How many chambers are in the human heart?', options_en = '["2","3","4","5"]' WHERE question = 'Сколько камер в сердце человека?';
UPDATE questions SET question_en = 'What is measured in hertz?', options_en = '["Power","Frequency","Voltage","Electric current"]' WHERE question = 'Что измеряется в герцах?';
UPDATE questions SET question_en = 'Which planet rotates "on its side"?', options_en = '["Neptune","Jupiter","Uranus","Venus"]' WHERE question = 'Какая планета вращается «лёжа на боку»?';
UPDATE questions SET question_en = 'What causes tides?', options_en = '["Wind","Earth''s rotation","The Moon''s gravity","Underwater currents"]' WHERE question = 'Что вызывает приливы и отливы?';
UPDATE questions SET question_en = 'What is the average salinity of the World Ocean?', options_en = '["1.5%","3.5%","5.5%","7.5%"]' WHERE question = 'Какова средняя солёность Мирового океана?';
UPDATE questions SET question_en = 'Which human organ consumes the most oxygen?', options_en = '["Heart","Liver","Brain","Muscles"]' WHERE question = 'Какой орган человека потребляет больше всего кислорода?';
UPDATE questions SET question_en = 'What is absolute zero temperature?', options_en = '["-100°C","-213°C","-273°C","-373°C"]' WHERE question = 'Чему равна абсолютный ноль температуры?';

-- 31-60: History and society
UPDATE questions SET question_en = 'Which emperor built the Great Wall of China?', options_en = '["Qin Shi Huang","Kublai Khan","Liu Bang","Emperor Wu"]' WHERE question = 'Какой император построил Великую Китайскую стену?';
UPDATE questions SET question_en = 'In what year was serfdom abolished in Russia?', options_en = '["1855","1861","1870","1883"]' WHERE question = 'В каком году отменили крепостное право в России?';
UPDATE questions SET question_en = 'Which treaty ended World War I?', options_en = '["Treaty of Westphalia","Treaty of Vienna","Treaty of Versailles","Treaty of Paris"]' WHERE question = 'Какой договор завершил Первую мировую войну?';
UPDATE questions SET question_en = 'Who was the last tsar of the Russian Empire?', options_en = '["Alexander III","Nicholas I","Nicholas II","Paul I"]' WHERE question = 'Кто был последним царём Российской империи?';
UPDATE questions SET question_en = 'In which country did the French Revolution take place?', options_en = '["England","France","Spain","Germany"]' WHERE question = 'В какой стране произошла Великая французская революция?';
UPDATE questions SET question_en = 'Who discovered the sea route to India?', options_en = '["Columbus","Vasco da Gama","Magellan","Drake"]' WHERE question = 'Кто открыл морской путь в Индию?';
UPDATE questions SET question_en = 'What was the name of Gagarin''s first spacecraft?', options_en = '["Soyuz","Voskhod","Vostok","Buran"]' WHERE question = 'Как назывался первый космический корабль Гагарина?';
UPDATE questions SET question_en = 'Which state was the first democracy?', options_en = '["Rome","Egypt","Athens","Carthage"]' WHERE question = 'Какое государство было первой демократией?';
UPDATE questions SET question_en = 'Which ruler united Egypt?', options_en = '["Ramesses","Tutankhamun","Narmer (Menes)","Cleopatra"]' WHERE question = 'Какой правитель объединил Египет?';
UPDATE questions SET question_en = 'In what year was the UN Universal Declaration of Human Rights adopted?', options_en = '["1945","1948","1950","1955"]' WHERE question = 'В каком году была принята Декларация прав человека ООН?';
UPDATE questions SET question_en = 'What event occurred on September 11, 2001?', options_en = '["Iraq War","Terrorist attack in New York","Tsunami in Asia","Earthquake in Japan"]' WHERE question = 'Какое событие произошло 11 сентября 2001 года?';
UPDATE questions SET question_en = 'Who was the first woman in space?', options_en = '["Savitskaya","Tereshkova","Ride","Kondakova"]' WHERE question = 'Кто был первой женщиной в космосе?';
UPDATE questions SET question_en = 'Which ancient civilization built Machu Picchu?', options_en = '["Aztecs","Maya","Incas","Olmecs"]' WHERE question = 'Какая древняя цивилизация построила Мачу-Пикчу?';
UPDATE questions SET question_en = 'In which century did the Industrial Revolution begin?', options_en = '["16th","17th","18th","19th"]' WHERE question = 'В каком веке началась промышленная революция?';
UPDATE questions SET question_en = 'Which country first gave women the right to vote?', options_en = '["USA","England","New Zealand","France"]' WHERE question = 'Какая страна первой дала женщинам право голоса?';
UPDATE questions SET question_en = 'Who wrote "Das Kapital"?', options_en = '["Lenin","Engels","Marx","Smith"]' WHERE question = 'Кто написал «Капитал»?';
UPDATE questions SET question_en = 'Which battle was the turning point in the War of 1812?', options_en = '["Austerlitz","Waterloo","Borodino","Trafalgar"]' WHERE question = 'Какое сражение стало переломным в войне 1812 года?';
UPDATE questions SET question_en = 'In what year did the USSR cease to exist?', options_en = '["1989","1990","1991","1993"]' WHERE question = 'В каком году СССР прекратил существование?';
UPDATE questions SET question_en = 'Who was the first chancellor of unified Germany (1871)?', options_en = '["Hitler","Bismarck","Wilhelm I","Adenauer"]' WHERE question = 'Кто был первым канцлером объединённой Германии (1871)?';
UPDATE questions SET question_en = 'Which war was fought between the North and South in the USA?', options_en = '["War of Independence","Civil War","Mexican War","Seven Years'' War"]' WHERE question = 'Какая война велась между Севером и Югом в США?';
UPDATE questions SET question_en = 'In what year did Columbus reach America?', options_en = '["1482","1492","1502","1512"]' WHERE question = 'В каком году Колумб достиг Америки?';
UPDATE questions SET question_en = 'Which city was the capital of Ancient Egypt?', options_en = '["Cairo","Alexandria","Memphis","Luxor"]' WHERE question = 'Какой город был столицей Древнего Египта?';
UPDATE questions SET question_en = 'Who commanded the French forces at Waterloo?', options_en = '["Louis XIV","Napoleon","Charlemagne","De Gaulle"]' WHERE question = 'Кто командовал французскими войсками при Ватерлоо?';
UPDATE questions SET question_en = 'In what year was the Battle of Stalingrad?', options_en = '["1941","1942-1943","1944","1945"]' WHERE question = 'В каком году была битва при Сталинграде?';
UPDATE questions SET question_en = 'Which people invented paper?', options_en = '["Egyptians","Romans","Chinese","Indians"]' WHERE question = 'Какой народ изобрёл бумагу?';
UPDATE questions SET question_en = 'What was the Viking state in Kyiv called?', options_en = '["Muscovy","Kievan Rus","Novgorod Republic","Khazar Khaganate"]' WHERE question = 'Как называлось государство викингов в Киеве?';
UPDATE questions SET question_en = 'In what year did the Korean War begin?', options_en = '["1948","1950","1952","1955"]' WHERE question = 'В каком году началась Корейская война?';
UPDATE questions SET question_en = 'Who was the first Roman emperor?', options_en = '["Julius Caesar","Augustus","Nero","Caligula"]' WHERE question = 'Кто был первым римским императором?';
UPDATE questions SET question_en = 'In what year did the Chernobyl disaster occur?', options_en = '["1984","1986","1988","1990"]' WHERE question = 'В каком году произошла Чернобыльская катастрофа?';
UPDATE questions SET question_en = 'What title did the rulers of Ancient Egypt hold?', options_en = '["King","Emperor","Pharaoh","Sultan"]' WHERE question = 'Какой титул носили правители Древнего Египта?';

-- 61-90: Geography
UPDATE questions SET question_en = 'Which country has the largest area in Africa?', options_en = '["Nigeria","Sudan","Algeria","Congo"]' WHERE question = 'Какая страна занимает наибольшую площадь в Африке?';
UPDATE questions SET question_en = 'In which city is the Taj Mahal located?', options_en = '["Delhi","Agra","Mumbai","Jaipur"]' WHERE question = 'В каком городе находится Тадж-Махал?';
UPDATE questions SET question_en = 'Which river flows through London?', options_en = '["Seine","Rhine","Thames","Danube"]' WHERE question = 'Какая река протекает через Лондон?';
UPDATE questions SET question_en = 'How many states are in the USA?', options_en = '["48","50","51","52"]' WHERE question = 'Сколько штатов в США?';
UPDATE questions SET question_en = 'Which capital is the northernmost in the world?', options_en = '["Oslo","Helsinki","Reykjavik","Stockholm"]' WHERE question = 'Какая столица самая северная в мире?';
UPDATE questions SET question_en = 'In which country is Kilimanjaro located?', options_en = '["Kenya","Tanzania","Uganda","Ethiopia"]' WHERE question = 'В какой стране находится Килиманджаро?';
UPDATE questions SET question_en = 'Which sea borders Egypt to the east?', options_en = '["Mediterranean","Red Sea","Black Sea","Arabian Sea"]' WHERE question = 'Какое море омывает Египет с востока?';
UPDATE questions SET question_en = 'Which strait separates Europe from Asia?', options_en = '["Strait of Gibraltar","Bosphorus","English Channel","Strait of Magellan"]' WHERE question = 'Какой пролив отделяет Европу от Азии?';
UPDATE questions SET question_en = 'Which country is shaped like a boot?', options_en = '["Spain","Greece","Italy","Portugal"]' WHERE question = 'Какая страна имеет форму сапога?';
UPDATE questions SET question_en = 'In which country is Angkor Wat located?', options_en = '["Thailand","Vietnam","Cambodia","Laos"]' WHERE question = 'В каком государстве находится Ангкор-Ват?';
UPDATE questions SET question_en = 'Which waterfall is the tallest in the world?', options_en = '["Niagara","Victoria","Angel Falls","Iguazu"]' WHERE question = 'Какой водопад самый высокий в мире?';
UPDATE questions SET question_en = 'What is the capital of New Zealand?', options_en = '["Auckland","Christchurch","Wellington","Dunedin"]' WHERE question = 'Столица Новой Зеландии?';
UPDATE questions SET question_en = 'Which island is the largest in the world?', options_en = '["Madagascar","Borneo","Greenland","New Guinea"]' WHERE question = 'Какой остров самый большой в мире?';
UPDATE questions SET question_en = 'Which country has the largest population?', options_en = '["India","China","USA","Indonesia"]' WHERE question = 'В какой стране больше всего населения?';
UPDATE questions SET question_en = 'Which river is the longest in Europe?', options_en = '["Danube","Rhine","Volga","Dnieper"]' WHERE question = 'Какая река самая длинная в Европе?';
UPDATE questions SET question_en = 'What is the capital of Thailand?', options_en = '["Phuket","Bangkok","Chiang Mai","Pattaya"]' WHERE question = 'Столица Таиланда?';
UPDATE questions SET question_en = 'Which is the largest desert in Asia?', options_en = '["Gobi","Karakum","Taklamakan","Arabian"]' WHERE question = 'Какая пустыня самая большая в Азии?';
UPDATE questions SET question_en = 'Which city is called the "Eternal City"?', options_en = '["Athens","Rome","Jerusalem","Istanbul"]' WHERE question = 'Какой город называют «Вечным»?';
UPDATE questions SET question_en = 'On which continent is Argentina located?', options_en = '["North America","South America","Europe","Africa"]' WHERE question = 'На каком континенте расположена Аргентина?';
UPDATE questions SET question_en = 'Which country produces the most coffee?', options_en = '["Colombia","Vietnam","Brazil","Ethiopia"]' WHERE question = 'Какая страна производит больше всего кофе?';
UPDATE questions SET question_en = 'What is the capital of Egypt?', options_en = '["Alexandria","Cairo","Luxor","Hurghada"]' WHERE question = 'Столица Египта?';
UPDATE questions SET question_en = 'In which country is Mount Fuji located?', options_en = '["China","Korea","Japan","Indonesia"]' WHERE question = 'В какой стране находится вулкан Фудзияма?';
UPDATE questions SET question_en = 'Which city is the capital of Switzerland?', options_en = '["Zurich","Geneva","Bern","Basel"]' WHERE question = 'Какой город является столицей Швейцарии?';
UPDATE questions SET question_en = 'Which country is spread across 17,000 islands?', options_en = '["Philippines","Indonesia","Malaysia","Japan"]' WHERE question = 'Какое государство расположено на 17 000 островах?';
UPDATE questions SET question_en = 'What is the capital of South Korea?', options_en = '["Busan","Pyongyang","Seoul","Incheon"]' WHERE question = 'Столица Южной Кореи?';
UPDATE questions SET question_en = 'Which canal connects the Atlantic and Pacific Oceans?', options_en = '["Suez","Panama","Kiel","Corinth"]' WHERE question = 'Какой канал соединяет Атлантический и Тихий океаны?';
UPDATE questions SET question_en = 'Which country is entirely located on islands in the Indian Ocean?', options_en = '["Sri Lanka","Maldives","Mauritius","All of the above"]' WHERE question = 'Какая страна целиком расположена на островах в Индийском океане?';
UPDATE questions SET question_en = 'What is the deepest point of the Mariana Trench called?', options_en = '["Drake Passage","Challenger Deep","Tonga Trench","Kermadec Trench"]' WHERE question = 'Как называется самая глубокая точка Марианской впадины?';
UPDATE questions SET question_en = 'Which river flows through Paris?', options_en = '["Rhine","Loire","Seine","Rhone"]' WHERE question = 'Какая река протекает через Париж?';
UPDATE questions SET question_en = 'What is the capital of Argentina?', options_en = '["Santiago","Montevideo","Buenos Aires","Lima"]' WHERE question = 'Столица Аргентины?';

-- 91-120: Movies and pop culture
UPDATE questions SET question_en = 'Who directed the Lord of the Rings trilogy?', options_en = '["Spielberg","Jackson","Cameron","Scott"]' WHERE question = 'Кто режиссёр трилогии «Властелин колец»?';
UPDATE questions SET question_en = 'Which actor played Tony Stark in the Marvel films?', options_en = '["Chris Evans","Robert Downey Jr.","Chris Hemsworth","Mark Ruffalo"]' WHERE question = 'Какой актёр играл Тони Старка в фильмах Marvel?';
UPDATE questions SET question_en = 'What is the name of Luke Skywalker''s planet?', options_en = '["Naboo","Tatooine","Coruscant","Hoth"]' WHERE question = 'Как называется планета Люка Скайуокера?';
UPDATE questions SET question_en = 'Which film won the Oscar for Best Picture in 2020?', options_en = '["1917","Joker","Parasite","Once Upon a Time in Hollywood"]' WHERE question = 'Какой фильм получил Оскар за лучший фильм в 2020 году?';
UPDATE questions SET question_en = 'Who played the Joker in "The Dark Knight"?', options_en = '["Jared Leto","Joaquin Phoenix","Heath Ledger","Jack Nicholson"]' WHERE question = 'Кто сыграл Джокера в фильме «Тёмный рыцарь»?';
UPDATE questions SET question_en = 'How many Infinity Stones are there in the Marvel films?', options_en = '["4","5","6","7"]' WHERE question = 'Сколько «Камней Бесконечности» в фильмах Marvel?';
UPDATE questions SET question_en = 'Which studio created the animated film "Totoro"?', options_en = '["Pixar","Disney","Studio Ghibli","DreamWorks"]' WHERE question = 'Какая студия создала мультфильм «Тотoro»?';
UPDATE questions SET question_en = 'Who directed "Pulp Fiction"?', options_en = '["Scorsese","Tarantino","Lynch","Coen Brothers"]' WHERE question = 'Кто режиссёр фильма «Криминальное чтиво»?';
UPDATE questions SET question_en = 'Which TV series is about a chemist who became a drug dealer?', options_en = '["Breaking Bad","The Wire","The Sopranos","Dexter"]' WHERE question = 'Какой сериал рассказывает о химике, ставшем наркоторговцем?';
UPDATE questions SET question_en = 'Which Pixar animated film is about emotions?', options_en = '["Up","WALL-E","Inside Out","Coco"]' WHERE question = 'Какой мультфильм Pixar рассказывает об эмоциях?';
UPDATE questions SET question_en = 'Who played Neo in "The Matrix"?', options_en = '["Brad Pitt","Keanu Reeves","Will Smith","Nicolas Cage"]' WHERE question = 'Кто сыграл Нео в «Матрице»?';
UPDATE questions SET question_en = 'In what year was the first "Star Wars" film released?', options_en = '["1975","1977","1979","1981"]' WHERE question = 'В каком году вышел первый фильм «Звёздные войны»?';
UPDATE questions SET question_en = 'What is the main character''s name in "Forrest Gump"?', options_en = '["Tom Gump","Forrest Gump","John Gump","Bill Gump"]' WHERE question = 'Как зовут главного героя «Форреста Гампа»?';
UPDATE questions SET question_en = 'Which actor played James Bond the most times?', options_en = '["Sean Connery","Roger Moore","Pierce Brosnan","Daniel Craig"]' WHERE question = 'Какой актёр сыграл Джеймса Бонда больше всех раз?';
UPDATE questions SET question_en = 'Who voices Woody in "Toy Story"?', options_en = '["Tim Allen","Tom Hanks","Robin Williams","Bill Murray"]' WHERE question = 'Кто озвучивает Вуди в мультфильме «История игрушек»?';
UPDATE questions SET question_en = 'In which film is the phrase "I am your father" said?', options_en = '["A New Hope","The Empire Strikes Back","Return of the Jedi","Revenge of the Sith"]' WHERE question = 'В каком фильме звучит фраза «Я — твой отец»?';
UPDATE questions SET question_en = 'Which film was Disney''s first full-length animated feature?', options_en = '["Pinocchio","Bambi","Snow White and the Seven Dwarfs","Fantasia"]' WHERE question = 'Какой фильм стал первым полнометражным мультфильмом Disney?';
UPDATE questions SET question_en = 'Who directed "Schindler''s List"?', options_en = '["Nolan","Spielberg","Scorsese","Kubrick"]' WHERE question = 'Кто режиссёр фильма «Список Шиндлера»?';
UPDATE questions SET question_en = 'In which universe does Batman exist?', options_en = '["Marvel","DC","Dark Horse","Image"]' WHERE question = 'В какой вселенной существует Бэтмен?';
UPDATE questions SET question_en = 'Which film series features Indiana Jones?', options_en = '["Raiders of the Lost Ark","Die Hard","Mission: Impossible","Jason Bourne"]' WHERE question = 'Какая серия фильмов рассказывает про Индиану Джонса?';
UPDATE questions SET question_en = 'Who created the animated series "The Simpsons"?', options_en = '["Seth MacFarlane","Matt Groening","Trey Parker","Mike Judge"]' WHERE question = 'Кто создал мультсериал «Симпсоны»?';
UPDATE questions SET question_en = 'Which Christopher Nolan film is about dreams?', options_en = '["Memento","Interstellar","Inception","The Prestige"]' WHERE question = 'Какой фильм Кристофера Нолана посвящён снам?';
UPDATE questions SET question_en = 'How many films are in the main Star Wars saga?', options_en = '["6","7","8","9"]' WHERE question = 'Сколько фильмов в основной саге «Звёздных войн»?';
UPDATE questions SET question_en = 'Who played Captain Jack Sparrow in "Pirates of the Caribbean"?', options_en = '["Orlando Bloom","Johnny Depp","Javier Bardem","Geoffrey Rush"]' WHERE question = 'Кто сыграл Джека Воробья в «Пиратах Карибского моря»?';
UPDATE questions SET question_en = 'Which anime film became the highest-grossing in Japan?', options_en = '["Your Name","Spirited Away","Demon Slayer","Howl''s Moving Castle"]' WHERE question = 'Какой аниме-фильм стал самым кассовым в Японии?';
UPDATE questions SET question_en = 'What is the fictional metal of Captain America''s shield called?', options_en = '["Adamantium","Mithril","Vibranium","Carbonadium"]' WHERE question = 'Как называется вымышленный металл щита Капитана Америки?';
UPDATE questions SET question_en = 'Who directed "Fight Club"?', options_en = '["Tarantino","Fincher","Nolan","Kubrick"]' WHERE question = 'Кто режиссёр «Бойцовского клуба»?';
UPDATE questions SET question_en = 'In what year was the first "Matrix" film released?', options_en = '["1997","1998","1999","2000"]' WHERE question = 'В каком году вышла первая часть «Матрицы»?';
UPDATE questions SET question_en = 'Which character says "Winter is coming"?', options_en = '["Cersei Lannister","Daenerys Targaryen","Ned Stark","Tyrion Lannister"]' WHERE question = 'Какой персонаж говорит «Зима близко»?';
UPDATE questions SET question_en = 'Which musical is about bartenders and dancers of Montmartre?', options_en = '["Chicago","Moulin Rouge","Cabaret","La La Land"]' WHERE question = 'Какой мюзикл рассказывает о барменах и танцорах Монмартра?';

-- 121-150: Music
UPDATE questions SET question_en = 'Which band released the album "Abbey Road"?', options_en = '["Rolling Stones","The Beatles","Led Zeppelin","Pink Floyd"]' WHERE question = 'Какой группе принадлежит альбом «Abbey Road»?';
UPDATE questions SET question_en = 'Who performed "Bohemian Rhapsody"?', options_en = '["Led Zeppelin","Queen","The Beatles","AC/DC"]' WHERE question = 'Кто исполнил «Bohemian Rhapsody»?';
UPDATE questions SET question_en = 'Which instrument is the largest in an orchestra?', options_en = '["Double bass","Tuba","Harp","Bass drum"]' WHERE question = 'Какой инструмент самый большой в оркестре?';
UPDATE questions SET question_en = 'Which country is ABBA from?', options_en = '["Norway","Denmark","Finland","Sweden"]' WHERE question = 'Из какой страны группа ABBA?';
UPDATE questions SET question_en = 'How many strings does a standard guitar have?', options_en = '["4","5","6","8"]' WHERE question = 'Сколько струн у стандартной гитары?';
UPDATE questions SET question_en = 'Who composed the "Moonlight Sonata"?', options_en = '["Mozart","Beethoven","Chopin","Liszt"]' WHERE question = 'Кто написал «Лунную сонату»?';
UPDATE questions SET question_en = 'What instrument is Stradivarius famous for?', options_en = '["Piano","Cello","Violin","Flute"]' WHERE question = 'Какой музыкальный инструмент Страдивари?';
UPDATE questions SET question_en = 'Which pop singer is known as the "King of Pop"?', options_en = '["Elvis Presley","Michael Jackson","Prince","Freddie Mercury"]' WHERE question = 'Какой поп-певец известен как «Король поп-музыки»?';
UPDATE questions SET question_en = 'How many strings does a violin have?', options_en = '["3","4","5","6"]' WHERE question = 'Сколько струн у скрипки?';
UPDATE questions SET question_en = 'Who was the lead vocalist of Nirvana?', options_en = '["Dave Grohl","Krist Novoselic","Kurt Cobain","Layne Staley"]' WHERE question = 'Кто является основным вокалистом группы Nirvana?';
UPDATE questions SET question_en = 'Which composer wrote "The Four Seasons"?', options_en = '["Bach","Vivaldi","Mozart","Handel"]' WHERE question = 'Какой композитор написал «Времена года»?';
UPDATE questions SET question_en = 'Which note is the lowest in standard notation?', options_en = '["C","D","A","G"]' WHERE question = 'Какая нота самая низкая в стандартной нотации?';
UPDATE questions SET question_en = 'Which country is reggae from?', options_en = '["Cuba","Trinidad","Jamaica","Haiti"]' WHERE question = 'Из какой страны родом регги?';
UPDATE questions SET question_en = 'Who composed the opera "Carmen"?', options_en = '["Verdi","Puccini","Bizet","Rossini"]' WHERE question = 'Кто написал оперу «Кармен»?';
UPDATE questions SET question_en = 'Which rapper has the alias Slim Shady?', options_en = '["Jay-Z","Eminem","Kanye West","Snoop Dogg"]' WHERE question = 'Какой рэпер имеет псевдоним Slim Shady?';
UPDATE questions SET question_en = 'Which rock festival took place in 1969?', options_en = '["Glastonbury","Coachella","Woodstock","Lollapalooza"]' WHERE question = 'Какой рок-фестиваль прошёл в 1969 году?';
UPDATE questions SET question_en = 'How many keys does a standard accordion have?', options_en = '["88","120","41","64"]' WHERE question = 'Сколько клавиш у стандартного аккордеона?';
UPDATE questions SET question_en = 'Who composed the ballet "Swan Lake"?', options_en = '["Prokofiev","Stravinsky","Tchaikovsky","Glinka"]' WHERE question = 'Кто написал балет «Лебединое озеро»?';
UPDATE questions SET question_en = 'Which instrument uses a reed to produce sound?', options_en = '["Flute","Trumpet","Clarinet","Trombone"]' WHERE question = 'Какой инструмент использует трость для звукоизвлечения?';
UPDATE questions SET question_en = 'Which musical term means "gradually louder"?', options_en = '["Piano","Forte","Crescendo","Diminuendo"]' WHERE question = 'Какой музыкальный термин означает «постепенно громче»?';
UPDATE questions SET question_en = 'Which band performed "Stairway to Heaven"?', options_en = '["Deep Purple","Led Zeppelin","Black Sabbath","Pink Floyd"]' WHERE question = 'Какая группа исполнила «Stairway to Heaven»?';
UPDATE questions SET question_en = 'Who composed the opera "La Traviata"?', options_en = '["Puccini","Rossini","Verdi","Mozart"]' WHERE question = 'Кто написал оперу «Травиата»?';
UPDATE questions SET question_en = 'Which musical style originated in Cuba?', options_en = '["Tango","Samba","Salsa","Flamenco"]' WHERE question = 'Какой музыкальный стиль зародился на Кубе?';
UPDATE questions SET question_en = 'Which singer is nicknamed "The Voice"?', options_en = '["Pavarotti","Sinatra","Bocelli","Domingo"]' WHERE question = 'Какой певец носит прозвище «Голос»?';
UPDATE questions SET question_en = 'Who wrote the unfinished "Requiem"?', options_en = '["Bach","Beethoven","Mozart","Haydn"]' WHERE question = 'Кто написал «Реквием», оставшийся незавершённым?';
UPDATE questions SET question_en = 'What musical interval is called an "octave"?', options_en = '["5 semitones","7 semitones","10 semitones","12 semitones"]' WHERE question = 'Какой музыкальный интервал называется «октава»?';
UPDATE questions SET question_en = 'Who is the lead vocalist of U2?', options_en = '["Sting","Bono","The Edge","Mick Jagger"]' WHERE question = 'Кто является ведущим вокалистом U2?';
UPDATE questions SET question_en = 'Which instrument plays the lowest notes in an orchestra?', options_en = '["Cello","Double bass","Contrabassoon","Tuba"]' WHERE question = 'Какой инструмент играет самые низкие ноты в оркестре?';
UPDATE questions SET question_en = 'Which song became the anthem of the 2010 FIFA World Cup?', options_en = '["We Are the Champions","Waka Waka","La Bamba","Macarena"]' WHERE question = 'Какая песня стала гимном ЧМ по футболу 2010?';
UPDATE questions SET question_en = 'Which musical sign raises a note by a semitone?', options_en = '["Flat","Natural","Sharp","Fermata"]' WHERE question = 'Какой знак в музыке повышает ноту на полтона?';

-- 151-180: Food, lifestyle and culture
UPDATE questions SET question_en = 'Which grain is sake made from?', options_en = '["Wheat","Barley","Rice","Corn"]' WHERE question = 'Из какого зерна делают саке?';
UPDATE questions SET question_en = 'Which spice is the most expensive in the world?', options_en = '["Vanilla","Cardamom","Saffron","Cinnamon"]' WHERE question = 'Какая специя самая дорогая в мире?';
UPDATE questions SET question_en = 'What is Japanese rice wine called?', options_en = '["Sake","Soju","Baijiu","Mirin"]' WHERE question = 'Как называется японское рисовое вино?';
UPDATE questions SET question_en = 'Which country does baklava originate from?', options_en = '["India","Turkey","Greece","The exact origin is disputed"]' WHERE question = 'Из какой страны родом пахлава?';
UPDATE questions SET question_en = 'Which cheese has blue mold?', options_en = '["Brie","Parmesan","Roquefort","Mozzarella"]' WHERE question = 'Какой сыр имеет голубую плесень?';
UPDATE questions SET question_en = 'How many calories are in one gram of protein?', options_en = '["2","4","7","9"]' WHERE question = 'Сколько калорий в одном грамме белка?';
UPDATE questions SET question_en = 'What is guacamole traditionally made from?', options_en = '["Tomato","Avocado","Cucumber","Pepper"]' WHERE question = 'Из чего традиционно готовят гуакамоле?';
UPDATE questions SET question_en = 'Which tea does not undergo fermentation?', options_en = '["Black","Green","Oolong","Pu-erh"]' WHERE question = 'Какой чай не подвергается ферментации?';
UPDATE questions SET question_en = 'Which dish is considered the national dish of Spain?', options_en = '["Pizza","Paella","Risotto","Tapas"]' WHERE question = 'Какое блюдо считается национальным в Испании?';
UPDATE questions SET question_en = 'Which vitamin is most abundant in carrots?', options_en = '["B","C","A","E"]' WHERE question = 'Какой витамин содержится в моркови больше всего?';
UPDATE questions SET question_en = 'What is the traditional Indian butter made from milk called?', options_en = '["Tahini","Ghee (clarified butter)","Coconut oil","Olive oil"]' WHERE question = 'Как называется традиционное индийское масло из молока?';
UPDATE questions SET question_en = 'Which fruit is depicted on the coat of arms of Granada?', options_en = '["Apple","Orange","Pomegranate","Lemon"]' WHERE question = 'Какой фрукт изображён на гербе Гранады?';
UPDATE questions SET question_en = 'What milk is real mozzarella made from?', options_en = '["Cow''s","Goat''s","Buffalo''s","Sheep''s"]' WHERE question = 'Из какого молока делают настоящую моцареллу?';
UPDATE questions SET question_en = 'Which alcoholic drink is made from grapes?', options_en = '["Beer","Whiskey","Wine","Rum"]' WHERE question = 'Какой алкогольный напиток делают из винограда?';
UPDATE questions SET question_en = 'What does the word "sushi" mean in Japanese?', options_en = '["Fish","Rice","Sour rice","Seafood"]' WHERE question = 'Что означает слово «суши» по-японски?';
UPDATE questions SET question_en = 'Which country does the croissant originate from?', options_en = '["France","Austria","Italy","Belgium"]' WHERE question = 'Из какой страны происходит круассан?';
UPDATE questions SET question_en = 'Which beverage is made from cacao beans?', options_en = '["Tea","Coffee","Chocolate","Mate"]' WHERE question = 'Какой напиток готовят из какао-бобов?';
UPDATE questions SET question_en = 'Which vegetable contains capsaicin?', options_en = '["Tomato","Chili pepper","Garlic","Onion"]' WHERE question = 'Какой овощ содержит капсаицин?';
UPDATE questions SET question_en = 'Which grain is polenta made from?', options_en = '["Wheat","Rice","Corn","Oats"]' WHERE question = 'Из какого злака делают поленту?';
UPDATE questions SET question_en = 'How many basic tastes can humans distinguish?', options_en = '["4","5","6","7"]' WHERE question = 'Сколько основных вкусов различает человек?';
UPDATE questions SET question_en = 'What is the taste called "umami"?', options_en = '["Spicy","Savory/meaty","Bitter","Astringent"]' WHERE question = 'Какой вкус называется «умами»?';
UPDATE questions SET question_en = 'Which beverage was invented in Ethiopia, according to legend?', options_en = '["Tea","Cocoa","Coffee","Mate"]' WHERE question = 'Какой напиток изобрели в Эфиопии по легенде?';
UPDATE questions SET question_en = 'What is the Italian dessert made from mascarpone and coffee called?', options_en = '["Panna cotta","Tiramisu","Cannoli","Profiteroles"]' WHERE question = 'Как называется итальянский десерт из маскарпоне и кофе?';
UPDATE questions SET question_en = 'What is wasabi?', options_en = '["Hot pepper","Japanese horseradish","Ginger","Mustard"]' WHERE question = 'Что такое васаби?';
UPDATE questions SET question_en = 'Which country is the largest producer of olive oil?', options_en = '["Italy","Greece","Spain","Tunisia"]' WHERE question = 'Какая страна — крупнейший производитель оливкового масла?';
UPDATE questions SET question_en = 'What is hummus made from?', options_en = '["Lentils","Chickpeas","Beans","Peas"]' WHERE question = 'Из чего готовят хумус?';
UPDATE questions SET question_en = 'Which fungus is used in the production of penicillin?', options_en = '["Champignon","Truffle","Penicillium","Fly agaric"]' WHERE question = 'Какой гриб используется при производстве пенициллина?';
UPDATE questions SET question_en = 'What is tequila made from?', options_en = '["Sugarcane","Agave","Corn","Potato"]' WHERE question = 'Из чего делают текилу?';
UPDATE questions SET question_en = 'Which product never spoils?', options_en = '["Salt","Sugar","Honey","Vinegar"]' WHERE question = 'Какой продукт никогда не портится?';
UPDATE questions SET question_en = 'Which berry is actually a fruit?', options_en = '["Strawberry","Banana","Watermelon","All of the above"]' WHERE question = 'Какая ягода на самом деле является фруктом?';

-- 181-210: Technology and internet
UPDATE questions SET question_en = 'What does the abbreviation Wi-Fi stand for?', options_en = '["Wireless Fidelity","Wireless Finder","Wide Frequency","Wire Free"]' WHERE question = 'Что означает аббревиатура Wi-Fi?';
UPDATE questions SET question_en = 'Which programming language was created by Sun Microsystems?', options_en = '["C#","Python","Java","Go"]' WHERE question = 'Какой язык программирования создала компания Sun Microsystems?';
UPDATE questions SET question_en = 'What is blockchain?', options_en = '["A type of processor","A distributed ledger","An antivirus","A programming language"]' WHERE question = 'Что такое блокчейн?';
UPDATE questions SET question_en = 'In what year was Instagram launched?', options_en = '["2008","2010","2012","2014"]' WHERE question = 'В каком году был запущен Instagram?';
UPDATE questions SET question_en = 'Who founded Amazon?', options_en = '["Bill Gates","Steve Jobs","Jeff Bezos","Larry Page"]' WHERE question = 'Кто основал Amazon?';
UPDATE questions SET question_en = 'What is a GPU?', options_en = '["General processor","Graphics processing unit","Gaming protocol","Global port"]' WHERE question = 'Что такое GPU?';
UPDATE questions SET question_en = 'Which protocol is used for sending email?', options_en = '["FTP","HTTP","SMTP","TCP"]' WHERE question = 'Какой протокол используется для отправки электронной почты?';
UPDATE questions SET question_en = 'Who created the C programming language?', options_en = '["Ken Thompson","Dennis Ritchie","Bjarne Stroustrup","Linus Torvalds"]' WHERE question = 'Кто создал язык программирования C?';
UPDATE questions SET question_en = 'What does SSD stand for?', options_en = '["Super Speed Disk","Solid State Drive","System Storage Device","Static System Data"]' WHERE question = 'Что означает SSD?';
UPDATE questions SET question_en = 'Which company created the first IBM PC?', options_en = '["Apple","IBM","HP","Dell"]' WHERE question = 'Какая компания создала первый персональный компьютер IBM PC?';
UPDATE questions SET question_en = 'What is a VPN?', options_en = '["Virtual private network","Visual port navigation","Virus program","High-speed transfer"]' WHERE question = 'Что такое VPN?';
UPDATE questions SET question_en = 'In what year did Bitcoin appear?', options_en = '["2007","2009","2011","2013"]' WHERE question = 'В каком году появился Bitcoin?';
UPDATE questions SET question_en = 'Which company developed ChatGPT?', options_en = '["Google","Meta","OpenAI","Microsoft"]' WHERE question = 'Какая компания разработала ChatGPT?';
UPDATE questions SET question_en = 'What is an API?', options_en = '["Application programming interface","A data type","A type of memory","A file format"]' WHERE question = 'Что такое API?';
UPDATE questions SET question_en = 'How many bytes are in one kilobyte?', options_en = '["100","512","1000","1024"]' WHERE question = 'Сколько байт в одном килобайте?';
UPDATE questions SET question_en = 'Which markup language is used for web pages?', options_en = '["CSS","JavaScript","HTML","Python"]' WHERE question = 'Какой язык разметки используется для веб-страниц?';
UPDATE questions SET question_en = 'Who founded SpaceX?', options_en = '["Jeff Bezos","Elon Musk","Richard Branson","Bill Gates"]' WHERE question = 'Кто основал SpaceX?';
UPDATE questions SET question_en = 'What is cloud storage?', options_en = '["Storage on a local disk","Storing data on remote servers","A type of RAM","A hard drive format"]' WHERE question = 'Что такое облачное хранилище?';
UPDATE questions SET question_en = 'Which top-level domain belongs to Japan?', options_en = '[".jp",".ja",".jn",".jap"]' WHERE question = 'Какой домен верхнего уровня принадлежит Японии?';
UPDATE questions SET question_en = 'In what year was the first PlayStation released?', options_en = '["1992","1994","1996","1998"]' WHERE question = 'В каком году вышла первая PlayStation?';
UPDATE questions SET question_en = 'What does IoT stand for?', options_en = '["Internet of Things","Information technology","Interactive terminal","Integrated optics"]' WHERE question = 'Что означает IoT?';
UPDATE questions SET question_en = 'Which company created the Bing search engine?', options_en = '["Google","Apple","Microsoft","Yahoo"]' WHERE question = 'Какая компания создала поисковую систему Bing?';
UPDATE questions SET question_en = 'What is phishing?', options_en = '["A type of fishing","Fraud through fake websites","A type of programming","An internet game"]' WHERE question = 'Что такое фишинг?';
UPDATE questions SET question_en = 'Which image format supports animation?', options_en = '["JPEG","PNG","GIF","BMP"]' WHERE question = 'Какой формат изображения поддерживает анимацию?';
UPDATE questions SET question_en = 'In what year was Twitter (X) founded?', options_en = '["2004","2006","2008","2010"]' WHERE question = 'В каком году был основан Twitter (X)?';
UPDATE questions SET question_en = 'What is two-factor authentication?', options_en = '["Two passwords","Verifying login with two methods","Two accounts","Double encryption"]' WHERE question = 'Что такое двухфакторная аутентификация?';
UPDATE questions SET question_en = 'What is the default port for HTTP?', options_en = '["21","25","80","443"]' WHERE question = 'Какой порт по умолчанию у HTTP?';
UPDATE questions SET question_en = 'Who created the first computer virus?', options_en = '["Richard Skrenta","Kevin Mitnick","John McAfee","Robert Morris"]' WHERE question = 'Кто создал первый компьютерный вирус?';
UPDATE questions SET question_en = 'Which format is used for e-books?', options_en = '["DOC","EPUB","MP3","AVI"]' WHERE question = 'Какой формат используется для электронных книг?';
UPDATE questions SET question_en = 'Which company manufactures Ryzen processors?', options_en = '["Intel","AMD","Qualcomm","Nvidia"]' WHERE question = 'Какая компания производит процессоры Ryzen?';

-- 211-240: Sports
UPDATE questions SET question_en = 'Which country won the first FIFA World Cup?', options_en = '["Brazil","Argentina","Uruguay","Italy"]' WHERE question = 'Какая страна выиграла первый чемпионат мира по футболу?';
UPDATE questions SET question_en = 'How many players are on a rugby team?', options_en = '["11","13","15","17"]' WHERE question = 'Сколько игроков в команде по регби?';
UPDATE questions SET question_en = 'Which tennis player has won the most Grand Slam titles (men)?', options_en = '["Federer","Nadal","Djokovic","Sampras"]' WHERE question = 'Какой теннисист выиграл больше всех турниров Большого шлема (мужчины)?';
UPDATE questions SET question_en = 'Which sport is played at Wimbledon?', options_en = '["Golf","Cricket","Tennis","Polo"]' WHERE question = 'Какой вид спорта проводится на Уимблдоне?';
UPDATE questions SET question_en = 'How many players are on a volleyball team on the court?', options_en = '["5","6","7","8"]' WHERE question = 'Сколько игроков в волейбольной команде на площадке?';
UPDATE questions SET question_en = 'In which city is the Camp Nou stadium located?', options_en = '["Madrid","Barcelona","Lisbon","Milan"]' WHERE question = 'В каком городе находится стадион «Камп Ноу»?';
UPDATE questions SET question_en = 'Which athlete won 8 gold medals at a single Olympics?', options_en = '["Bolt","Phelps","Thorpe","Spitz"]' WHERE question = 'Какой спортсмен выиграл 8 золотых медалей на одной Олимпиаде?';
UPDATE questions SET question_en = 'Which sport is called the "gentleman''s game"?', options_en = '["Golf","Cricket","Polo","Tennis"]' WHERE question = 'Какой вид спорта называют «джентльменской игрой»?';
UPDATE questions SET question_en = 'How many periods are in a hockey game?', options_en = '["2","3","4","5"]' WHERE question = 'Сколько периодов в хоккейном матче?';
UPDATE questions SET question_en = 'Which team has won the most Champions League titles?', options_en = '["AC Milan","Barcelona","Real Madrid","Liverpool"]' WHERE question = 'Какая команда выиграла больше всего Лиг чемпионов?';
UPDATE questions SET question_en = 'In which sport is the term "knockout" used?', options_en = '["Wrestling","Boxing","Judo","Fencing"]' WHERE question = 'В каком виде спорта есть термин «нокаут»?';
UPDATE questions SET question_en = 'Which ball is the heaviest?', options_en = '["Tennis ball","Volleyball","Bowling ball","Basketball"]' WHERE question = 'Какой мяч самый тяжёлый?';
UPDATE questions SET question_en = 'In what year will the next Summer Olympics after 2024 be held?', options_en = '["2026","2028","2030","2032"]' WHERE question = 'В каком году пройдут следующие летние Олимпийские игры после 2024?';
UPDATE questions SET question_en = 'What is the distance between bases in baseball?', options_en = '["18.44 m","27.43 m","30.48 m","36.58 m"]' WHERE question = 'Какое расстояние между базами в бейсболе?';
UPDATE questions SET question_en = 'Which sport includes elements like "toe loop" and "axel"?', options_en = '["Gymnastics","Figure skating","Ballet","Acrobatics"]' WHERE question = 'Какой вид спорта включает элементы «тулуп» и «аксель»?';
UPDATE questions SET question_en = 'How many serves are allowed per point in tennis?', options_en = '["1","2","3","Unlimited"]' WHERE question = 'Сколько подач даётся в теннисе на каждое очко?';
UPDATE questions SET question_en = 'Which football club is known as the "Red Devils"?', options_en = '["Liverpool","Arsenal","Manchester United","Bayern Munich"]' WHERE question = 'Какой футбольный клуб известен как «красные дьяволы»?';
UPDATE questions SET question_en = 'In which sport is a foil used?', options_en = '["Archery","Fencing","Javelin throw","Biathlon"]' WHERE question = 'В каком виде спорта используют рапиру?';
UPDATE questions SET question_en = 'What is the shortest swimming distance at the Olympics?', options_en = '["25 m","50 m","100 m","200 m"]' WHERE question = 'Какая дистанция в плавании самая короткая на Олимпиаде?';
UPDATE questions SET question_en = 'Which Formula 1 driver has the most wins in history?', options_en = '["Schumacher","Hamilton","Verstappen","Senna"]' WHERE question = 'Какой формулы 1 гонщик имеет больше всех побед в истории?';
UPDATE questions SET question_en = 'In which sport are there "outs", "strikes", and "home runs"?', options_en = '["Cricket","Softball","Baseball","Lacrosse"]' WHERE question = 'В каком виде спорта есть «аут», «страйк» и «хоум-ран»?';
UPDATE questions SET question_en = 'Which swimmer is known as the "Baltimore Bullet"?', options_en = '["Ian Thorpe","Ryan Lochte","Michael Phelps","Mark Spitz"]' WHERE question = 'Какой пловец известен как «Балтиморская пуля»?';
UPDATE questions SET question_en = 'Which sport is popular in Ireland and involves a stick and ball?', options_en = '["Cricket","Hurling","Lacrosse","Polo"]' WHERE question = 'Какой спорт популярен в Ирландии с клюшкой и мячом?';
UPDATE questions SET question_en = 'How many games do you need to win to take a set in tennis?', options_en = '["4","5","6","7"]' WHERE question = 'Сколько геймов нужно выиграть для взятия сета в теннисе?';
UPDATE questions SET question_en = 'Which martial art is included in the Olympic Games program?', options_en = '["Kickboxing","Taekwondo","Muay Thai","MMA"]' WHERE question = 'Какое единоборство включено в программу Олимпийских игр?';
UPDATE questions SET question_en = 'How many fouls lead to ejection in NBA basketball?', options_en = '["4","5","6","7"]' WHERE question = 'Сколько фолов нужно для удаления в баскетболе NBA?';
UPDATE questions SET question_en = 'In what year was the first Super Bowl held?', options_en = '["1960","1963","1967","1970"]' WHERE question = 'В каком году прошёл первый Супербоул?';
UPDATE questions SET question_en = 'Which sport is popular in India besides cricket?', options_en = '["Baseball","Field hockey","Rugby","Lacrosse"]' WHERE question = 'Какой вид спорта популярен в Индии кроме крикета?';
UPDATE questions SET question_en = 'What is the standard football field length?', options_en = '["90-100 m","100-110 m","110-120 m","120-130 m"]' WHERE question = 'Какой размер имеет стандартное футбольное поле (длина)?';
UPDATE questions SET question_en = 'In which city were the 2016 Olympic Games held?', options_en = '["London","Beijing","Rio de Janeiro","Tokyo"]' WHERE question = 'В каком городе проходили Олимпийские игры 2016?';

-- 241-270: Animals, space, nature
UPDATE questions SET question_en = 'Which animal can hold its breath the longest?', options_en = '["Dolphin","Sperm whale","Sea turtle","Cuvier''s beaked whale"]' WHERE question = 'Какое животное может задерживать дыхание дольше всех?';
UPDATE questions SET question_en = 'How many planets in the Solar System have rings?', options_en = '["1","2","3","4"]' WHERE question = 'Сколько планет в Солнечной системе имеют кольца?';
UPDATE questions SET question_en = 'Which bird is the fastest in a dive?', options_en = '["Eagle","Peregrine falcon","Hawk","Swift"]' WHERE question = 'Какая птица самая быстрая в пикировании?';
UPDATE questions SET question_en = 'Which animal never sleeps?', options_en = '["Giraffe","Ant","Shark","Bullfrog"]' WHERE question = 'Какое животное никогда не спит?';
UPDATE questions SET question_en = 'Which star is the closest to the Sun?', options_en = '["Sirius","Proxima Centauri","Alpha Centauri A","Betelgeuse"]' WHERE question = 'Какая звезда ближайшая к Солнцу?';
UPDATE questions SET question_en = 'Which is the only continent without reptiles?', options_en = '["Australia","Arctic","Antarctica","None"]' WHERE question = 'Какой единственный континент без рептилий?';
UPDATE questions SET question_en = 'Which planet has the strongest winds?', options_en = '["Jupiter","Saturn","Neptune","Uranus"]' WHERE question = 'Какая планета имеет самый сильный ветер?';
UPDATE questions SET question_en = 'Which animal has the longest gestation period?', options_en = '["Whale","Elephant","Giraffe","Rhinoceros"]' WHERE question = 'Какое животное имеет самый длинный период беременности?';
UPDATE questions SET question_en = 'What type of star is the Sun?', options_en = '["Red dwarf","Yellow dwarf","White dwarf","Red giant"]' WHERE question = 'Какой тип звезды — Солнце?';
UPDATE questions SET question_en = 'Which animal can survive in outer space?', options_en = '["Cockroach","Tardigrade","Scorpion","Jellyfish"]' WHERE question = 'Какое животное может выжить в открытом космосе?';
UPDATE questions SET question_en = 'How many moons does Mars have?', options_en = '["0","1","2","4"]' WHERE question = 'Сколько спутников у Марса?';
UPDATE questions SET question_en = 'Which mammal lays eggs?', options_en = '["Koala","Platypus","Opossum","Hedgehog"]' WHERE question = 'Какое млекопитающее откладывает яйца?';
UPDATE questions SET question_en = 'Which galaxy is the closest to the Milky Way?', options_en = '["Triangulum","Andromeda","Magellanic Clouds","Centaurus A"]' WHERE question = 'Какая галактика ближайшая к Млечному Пути?';
UPDATE questions SET question_en = 'Which animal can regenerate its heart?', options_en = '["Lizard","Axolotl","Starfish","Earthworm"]' WHERE question = 'Какое животное может регенерировать сердце?';
UPDATE questions SET question_en = 'How long is one day on Venus (in Earth days)?', options_en = '["58","116","243","365"]' WHERE question = 'Сколько длится один день на Венере (в земных днях)?';
UPDATE questions SET question_en = 'Which is the most venomous snake in the world?', options_en = '["Black mamba","Taipan","King cobra","Belcher''s sea snake"]' WHERE question = 'Какая самая ядовитая змея в мире?';
UPDATE questions SET question_en = 'Which planet rotates in the opposite direction?', options_en = '["Mars","Venus","Uranus","Pluto"]' WHERE question = 'Какая планета вращается в обратном направлении?';
UPDATE questions SET question_en = 'Which tree lives the longest?', options_en = '["Oak","Baobab","Bristlecone pine","Sequoia"]' WHERE question = 'Какое дерево живёт дольше всех?';
UPDATE questions SET question_en = 'Which animal has blue blood?', options_en = '["Squid","Horseshoe crab","Octopus","All of the above"]' WHERE question = 'Какое животное имеет синюю кровь?';
UPDATE questions SET question_en = 'Which ocean is the smallest?', options_en = '["Indian","Atlantic","Arctic","Southern"]' WHERE question = 'Какой океан самый маленький?';
UPDATE questions SET question_en = 'Which animal can run immediately after birth?', options_en = '["Cat","Bear","Horse","Dog"]' WHERE question = 'Какое животное может бегать сразу после рождения?';
UPDATE questions SET question_en = 'How much does the ISS weigh approximately?', options_en = '["100 tons","200 tons","420 tons","800 tons"]' WHERE question = 'Сколько весит МКС примерно?';
UPDATE questions SET question_en = 'Which animal sleeps up to 22 hours a day?', options_en = '["Sloth","Koala","Cat","Ferret"]' WHERE question = 'Какое животное спит до 22 часов в сутки?';
UPDATE questions SET question_en = 'What is the tallest mountain in the Solar System?', options_en = '["Everest","Olympus Mons on Mars","Maxwell Montes on Venus","Rhea on the Moon"]' WHERE question = 'Какая самая высокая гора в Солнечной системе?';
UPDATE questions SET question_en = 'Which species of shark is the largest?', options_en = '["Great white shark","Tiger shark","Whale shark","Greenland shark"]' WHERE question = 'Какой вид акул самый крупный?';
UPDATE questions SET question_en = 'How many teeth does a dolphin have?', options_en = '["0","50-60","80-100","200+"]' WHERE question = 'Сколько зубов у дельфина?';
UPDATE questions SET question_en = 'Which insect is the strongest relative to its weight?', options_en = '["Ant","Dung beetle","Bee","Flea"]' WHERE question = 'Какое насекомое является самым сильным относительно своего веса?';
UPDATE questions SET question_en = 'On which planet does it rain diamonds?', options_en = '["Jupiter","Neptune","Saturn","Both Neptune and Saturn"]' WHERE question = 'На какой планете идут алмазные дожди?';
UPDATE questions SET question_en = 'Which animal has the longest migration?', options_en = '["Monarch butterfly","Arctic tern","Gray whale","Humpback whale"]' WHERE question = 'Какая самая длинная миграция среди животных?';
UPDATE questions SET question_en = 'How many rings does Saturn have?', options_en = '["3","7","Thousands","No exact number"]' WHERE question = 'Сколько колец у Сатурна?';

-- 271-300: Literature, art, mathematics, miscellaneous
UPDATE questions SET question_en = 'Who wrote "The Divine Comedy"?', options_en = '["Petrarch","Boccaccio","Dante","Virgil"]' WHERE question = 'Кто написал «Божественную комедию»?';
UPDATE questions SET question_en = 'What number does the Roman numeral L represent?', options_en = '["10","50","100","500"]' WHERE question = 'Какое число обозначает римская цифра L?';
UPDATE questions SET question_en = 'Who wrote "Don Quixote"?', options_en = '["Lope de Vega","Cervantes","Calderon","Garcia Lorca"]' WHERE question = 'Кто написал «Дон Кихот»?';
UPDATE questions SET question_en = 'What is the square root of 144?', options_en = '["10","11","12","14"]' WHERE question = 'Чему равен квадратный корень из 144?';
UPDATE questions SET question_en = 'Who wrote "Hamlet"?', options_en = '["Moliere","Goethe","Shakespeare","Schiller"]' WHERE question = 'Кто написал «Гамлет»?';
UPDATE questions SET question_en = 'Which painting style does Claude Monet represent?', options_en = '["Cubism","Impressionism","Surrealism","Expressionism"]' WHERE question = 'Какой стиль живописи представляет Клод Моне?';
UPDATE questions SET question_en = 'How many faces does a cube have?', options_en = '["4","6","8","12"]' WHERE question = 'Сколько граней у куба?';
UPDATE questions SET question_en = 'Who painted "The Scream"?', options_en = '["Munch","Dali","Picasso","Magritte"]' WHERE question = 'Кто автор картины «Крик»?';
UPDATE questions SET question_en = 'Which number is a Fibonacci number?', options_en = '["4","7","9","13"]' WHERE question = 'Какое число является числом Фибоначчи?';
UPDATE questions SET question_en = 'Who wrote "Anna Karenina"?', options_en = '["Turgenev","Tolstoy","Dostoevsky","Goncharov"]' WHERE question = 'Кто написал «Анну Каренину»?';
UPDATE questions SET question_en = 'What is the angle in an equilateral triangle?', options_en = '["45°","60°","90°","120°"]' WHERE question = 'Какой угол в равностороннем треугольнике?';
UPDATE questions SET question_en = 'Who created "The Persistence of Memory" (melting clocks)?', options_en = '["Picasso","Magritte","Dali","Kandinsky"]' WHERE question = 'Кто создал «Постоянство памяти» (мягкие часы)?';
UPDATE questions SET question_en = 'Which number is not prime?', options_en = '["2","3","9","11"]' WHERE question = 'Какое число не является простым?';
UPDATE questions SET question_en = 'Who wrote "The Three Musketeers"?', options_en = '["Hugo","Dumas","Balzac","Stendhal"]' WHERE question = 'Кто написал «Три мушкетёра»?';
UPDATE questions SET question_en = 'What architectural style is Notre-Dame Cathedral?', options_en = '["Romanesque","Gothic","Baroque","Renaissance"]' WHERE question = 'Какой архитектурный стиль у собора Нотр-Дам?';
UPDATE questions SET question_en = 'What is 2 to the power of 10?', options_en = '["256","512","1024","2048"]' WHERE question = 'Чему равно 2 в степени 10?';
UPDATE questions SET question_en = 'Who wrote "One Hundred Years of Solitude"?', options_en = '["Borges","Marquez","Cortazar","Allende"]' WHERE question = 'Кто написал «Сто лет одиночества»?';
UPDATE questions SET question_en = 'What color do you get when mixing blue and yellow?', options_en = '["Orange","Purple","Green","Brown"]' WHERE question = 'Какой цвет получится при смешении синего и жёлтого?';
UPDATE questions SET question_en = 'What is the "Golden Ratio" approximately?', options_en = '["1.414","1.618","2.236","3.142"]' WHERE question = 'Что такое «Золотое сечение» приблизительно?';
UPDATE questions SET question_en = 'Who is the author of "The Metamorphosis"?', options_en = '["Hesse","Kafka","Mann","Musil"]' WHERE question = 'Кто автор «Превращения» (Metamorphosis)?';
UPDATE questions SET question_en = 'How many vertices does a pyramid with a square base have?', options_en = '["4","5","6","8"]' WHERE question = 'Сколько вершин у пирамиды с квадратным основанием?';
UPDATE questions SET question_en = 'Who painted "Girl with Peaches"?', options_en = '["Repin","Serov","Levitan","Vrubel"]' WHERE question = 'Кто нарисовал «Девочку с персиками»?';
UPDATE questions SET question_en = 'Which mathematical symbol denotes factorial?', options_en = '["+","*","!","#"]' WHERE question = 'Какой знак в математике обозначает факториал?';
UPDATE questions SET question_en = 'Who created the sculpture "The Thinker"?', options_en = '["Michelangelo","Bernini","Rodin","Canova"]' WHERE question = 'Кто создал скульптуру «Мыслитель»?';
UPDATE questions SET question_en = 'How many millimeters are in one meter?', options_en = '["10","100","1000","10000"]' WHERE question = 'Сколько миллиметров в одном метре?';
UPDATE questions SET question_en = 'Who wrote "Fahrenheit 451"?', options_en = '["Orwell","Huxley","Bradbury","Asimov"]' WHERE question = 'Кто написал «451 градус по Фаренгейту»?';
UPDATE questions SET question_en = 'Which theater is considered the main one in Russia?', options_en = '["Mariinsky","Bolshoi","Moscow Art Theatre","Alexandrinsky"]' WHERE question = 'Какой театр считается главным в России?';
UPDATE questions SET question_en = 'What is the sum of angles in a triangle?', options_en = '["90°","180°","270°","360°"]' WHERE question = 'Чему равна сумма углов треугольника?';
UPDATE questions SET question_en = 'Who wrote "The Catcher in the Rye"?', options_en = '["Fitzgerald","Hemingway","Salinger","Kerouac"]' WHERE question = 'Кто написал «Над пропастью во ржи»?';
UPDATE questions SET question_en = 'Which artist cut off part of his ear?', options_en = '["Picasso","Monet","Van Gogh","Dali"]' WHERE question = 'Какой художник отрезал себе часть уха?';
